### ISSUE TITLE
Speaking rate possible via embedded speech commands

### ISSUE THREAD

**Issue by jmmitchell** [mklement0/speak.awf#2]
In the comments of the say-it bash script, it is noted that as of OSX 10.11 the `say` command doesn't respect custom speaking rates. I noted that apple supports other methods of indicating the speed via embedded speech commands. You might want to look into them as another method of specifying the rate.

[StackExchange discussion](https://superuser.com/questions/679099/is-it-possible-to-change-the-speech-rate-in-os-x-say-command)

[Apple Dev: Techniques for Customizing Synthesized Speech](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/SpeechSynthesisProgrammingGuide/FineTuning/FineTuning.html#//apple_ref/doc/uid/TP40004365-CH5-SW3)

**Comment by mklement0** [comment]
Thanks for the pointers, @jmmitchell.

What the comment in `say-it` is trying to say is that `say` doesn't respect custom speaking rates _if you use the `-v` option_ to target a voice explicitly.

E.g., if you've set rate `100` for voice `Alex` via `System Preferences` and `Alex` is the default voice, `say 'Hello'` _will_ honor the rate, but `say -v Alex 'Hello'` will _not_.

`say-it` compensates for that by reading the custom rates from configuration and applying them explicitly, via `-r <rate>` when `say` is invoked behind the scenes.
